### ISSUE TITLE
Il titolo inizia con la minuscola

### ISSUE THREAD

**Issue by Mellgood** [excellence3/portfolios#1]
Ho notato che il titolo del Readme inizia con la minuscola. Dovrebbe inizare con la maiuscola!

**Comment by GretaDMR** [comment]
Ma quando mai?!

**Comment by AntoCirullo** [comment]
ok

**Comment by SebastianCiuraru** [comment]
Okey lesgo!

**Comment by eletodosdias** [comment]
ma il colore ti va beneeeeee?!?!
